// eslint.config.mjs — the single lint owner (Biome is formatter/organizer only).
// Implements BUILD-SPEC §Lint: typescript-eslint strictTypeChecked + stylisticTypeChecked
// via projectService, jsx-a11y strict scoped to the desktop SPA, react-hooks with the
// merged React Compiler rules, sonarjs cognitive-complexity <= 15, and the two
// no-restricted-imports boundary bans. Runs as `eslint . --max-warnings 0`.
import jsxA11y from 'eslint-plugin-jsx-a11y'
import reactHooks from 'eslint-plugin-react-hooks'
import sonarjs from 'eslint-plugin-sonarjs'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    // Build outputs, generated code, and non-app surfaces owned by other gates.
    ignores: [
      '**/dist/**',
      '**/dist-types/**', // composite tsc -b declaration output (runs before lint in the gate chain)
      '**/target/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'apps/desktop/src/ipc/bindings.ts', // generated by tauri-specta; drift-gated, not linted
      'apps/desktop/src-tauri/**', // Rust host: clippy owns it
      'apps/desktop/isolation/**', // dependency-free Tauri isolation shim (plain JS)
      'packages/schema/drizzle/**', // generated SQL migrations + snapshots
      'tools/**', // gate scripts: plain node, guarded by the harness itself
      'tests/**', // root-level RLS runner surface (gates wave)
      'db/**',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    extends: [...tseslint.configs.strictTypeChecked, ...tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        // projectService discovers each workspace tsconfig; root-level config files
        // (vitest.config.ts) belong to no project and use the default project.
        projectService: {
          allowDefaultProject: ['*.config.ts'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error', // a stale suppression is itself a lint error
    },
    plugins: { sonarjs },
    rules: {
      // SOURCE: BUILD-SPEC §Lint (cognitive-complexity 15 error, replaces blanket max-lines) [corpus: harness/doctrine]
      'sonarjs/cognitive-complexity': ['error', 15],
    },
  },
  {
    // Desktop SPA: WCAG-strict a11y + hooks + React Compiler rules.
    files: ['apps/desktop/**/*.ts', 'apps/desktop/**/*.tsx'],
    extends: [jsxA11y.flatConfigs.strict, reactHooks.configs.flat.recommended],
    rules: {
      // recommended ships this as a warning; --max-warnings 0 makes warns fatal anyway,
      // so declare the real severity instead of tripping the warning budget.
      'react-hooks/exhaustive-deps': 'error',
    },
  },
  {
    // Tauri APIs only through the src/ipc facade (and the keyboard registry, which
    // wraps global-shortcut handling). Everything else gets typed wrappers from ipc/.
    // SOURCE: BUILD-SPEC §Tauri (UI imports tauri APIs ONLY via src/ipc/) [corpus: tauri/isolation]
    files: ['apps/desktop/src/**'],
    ignores: ['apps/desktop/src/ipc/**', 'apps/desktop/src/keyboard/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@tauri-apps/api', '@tauri-apps/api/*', '@tauri-apps/plugin-*'],
              message:
                'Import Tauri APIs only via src/ipc/ (typed, mockable facade) or src/keyboard/.',
            },
          ],
        },
      ],
    },
  },
  {
    // Matrix/graph feature surfaces render via canvas/manual SVG for performance and
    // a11y-tree control; charting libraries are banned there. This block is LAST so it
    // also restates the Tauri ban — later flat-config blocks replace rule entries wholesale.
    files: ['apps/desktop/src/features/matrix/**', 'apps/desktop/src/features/graph/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['recharts', 'recharts/*', 'visx', '@visx/*', 'd3-selection', '@nivo/*'],
              message:
                'matrix/graph features draw their own canvas/SVG; chart libraries are banned here.',
            },
            {
              group: ['@tauri-apps/api', '@tauri-apps/api/*', '@tauri-apps/plugin-*'],
              message:
                'Import Tauri APIs only via src/ipc/ (typed, mockable facade) or src/keyboard/.',
            },
          ],
        },
      ],
    },
  },
)
