// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Host (crate) version. The version-sync gate keeps this crate,
	 *  `tauri.conf.json`, and the workspace package versions in lockstep.
	 */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
};

