#!/usr/bin/env node
// Gate: notices — third-party attribution drift (ci-provenance module).
// Regenerates NOTICES.md from the LIVE production dependency set (`pnpm licenses
// list --prod --json`) and compares it byte-for-byte to the committed file. A
// dependency added, removed, or relicensed without a NOTICES update fails here —
// attribution files rot silently otherwise, and several permissive licenses
// (Apache-2.0 §4d, BSD) make shipping stale notices a compliance defect.
//   node tools/check-notices.mjs           # check (the CI gate)
//   node tools/check-notices.mjs --write   # regenerate NOTICES.md (then review + commit)
// SOURCE: docs/harness/gates-catalog.md (ci-provenance module — NOTICES drift)
import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fail, ok, skipOrFail } from './lib/gate.mjs'

const GATE = 'notices'
const NOTICES_PATH = 'NOTICES.md'

let raw
try {
  raw = execSync('pnpm licenses list --prod --json', {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'pipe'],
  })
} catch {
  skipOrFail(GATE, 'pnpm licenses failed (no install yet? run pnpm install)')
}

// pnpm shape: { "<license>": [ { name, versions | version, ... }, ... ] }
let byLicense
try {
  byLicense = JSON.parse(raw)
} catch {
  fail(GATE, 'could not parse `pnpm licenses list --prod --json` output')
}

const lines = [
  '# Third-party notices',
  '',
  'Generated by `node tools/check-notices.mjs --write` from the production',
  'dependency set. Do not edit by hand — CI (ci-provenance module) fails on drift.',
  '',
]
for (const license of Object.keys(byLicense).sort()) {
  lines.push(`## ${license}`, '')
  const entries = byLicense[license]
    .map((pkg) => {
      const versions = Array.isArray(pkg.versions) ? pkg.versions : [pkg.version]
      return `- ${pkg.name} (${versions.filter(Boolean).sort().join(', ')})`
    })
    .sort()
  lines.push(...entries, '')
}
const generated = `${lines.join('\n').trimEnd()}\n`

if (process.argv.includes('--write')) {
  writeFileSync(NOTICES_PATH, generated)
  ok(GATE, `wrote ${NOTICES_PATH} — review the diff and commit it`)
}

if (!existsSync(NOTICES_PATH)) {
  fail(
    GATE,
    `${NOTICES_PATH} does not exist — run \`node tools/check-notices.mjs --write\` once and commit the result`,
  )
}

const committed = readFileSync(NOTICES_PATH, 'utf8')
if (committed !== generated) {
  fail(
    GATE,
    `${NOTICES_PATH} drifted from the live dependency set — run \`node tools/check-notices.mjs --write\`, review, and commit`,
  )
}
ok(GATE, `${NOTICES_PATH} matches the production dependency set`)
